### PR TITLE
Require auth to hit AI endpoints

### LINKED ISSUE #231: AI functionality not protected by auth
## Issue
`ai_routes.js` does not use the `UserAuth` middleware that checks auth and therefore can be accessed by anyone on the internet that finds the endpoint.

A simple solution is to just add the `UserAuth.isSignedIn` middleware to this endpoint.

## Future Prevention
Unfortunately, this is an easy mistake to make. I'm not familiar with a way to make this secure by default. It would be nice to make endpoints require auth by default and require explicit specification to make an endpoint no-auth. Maybe there is a way, but I have not looked into it in years.

Alternatively, we could add some sort of static code analysis that will fail builds/some sort of test if they do not have a middleware specified.

At the very least, maybe adding some docs explaining to use the auth middleware/how it works.

Note: This bug was introduced in #156

### PR DESCRIPTION
**Pull request by RogerTheRabbit**
Resolves: https://github.com/RIT-Software-Engineering/RIT-SE-Senior-Project/pull/220

### CODE REVIEW

File: server/server/routing/ai_routes.js [hunk 1]
```diff
@@ -83,7 +84,7 @@ async function provide_summary(studentFeedback) {
 }
 
 module.exports = () => {
-  router.post("/GenerateSummary", (req, res, next) => {
+  router.post("/GenerateSummary", [UserAuth.isSignedIn], (req, res, next) => {
```
Comment (RogerTheRabbit) [inline server/server/routing/ai_routes.js]: Not sure what the specific auth we want here is. This middleware checks that you at least need to be signed in, but not sure if we want to restrict this further so that only coaches or admins can access this. This can easily be done by using `isCoachOrAdmin` or `isAdmin`. Code for these middleware are [here](https://github.com/RIT-Software-Engineering/RIT-SE-Senior-Project/blob/dev/server/server/routing/user_auth.js)
